import fs from "node:fs/promises";

const owner=process.env.GITHUB_REPOSITORY?.split("/")[0]||"Ivy-forever18";
const repo=process.env.GITHUB_REPOSITORY?.split("/")[1]||"frontier-weekly";
const token=process.env.GITHUB_TOKEN;
const apiKey=process.env.DEEPSEEK_API_KEY;
const model=process.env.DEEPSEEK_MODEL||"deepseek-v4-flash";
if(!apiKey) throw new Error("请在 GitHub Actions Secrets 中配置 DEEPSEEK_API_KEY");
const cutoff=Date.now()-7*24*60*60*1000;

const strip=s=>String(s||"").replace(/<!\[CDATA\[|\]\]>/g,"").replace(/<[^>]+>/g," ").replace(/&amp;/g,"&").replace(/\s+/g," ").trim();
const tag=(xml,name)=>[...xml.matchAll(new RegExp(`<${name}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${name}>`,"gi"))].map(m=>strip(m[1]));
async function feeds(){const sources=JSON.parse(await fs.readFile("data/sources.json","utf8"));const out=[];for(const s of sources.filter(x=>x.enabled)){try{const xml=await fetch(s.url,{headers:{"user-agent":"frontier-weekly/1.0"}}).then(r=>{if(!r.ok)throw new Error(String(r.status));return r.text()});const blocks=[...xml.matchAll(/<(item|entry)(?:\s[^>]*)?>([\s\S]*?)<\/\1>/gi)].slice(0,50);for(const [, ,b] of blocks){const title=tag(b,"title")[0],summary=tag(b,"description")[0]||tag(b,"summary")[0]||"";const href=b.match(/<link[^>]+href=["']([^"']+)/i)?.[1]||tag(b,"link")[0];const published=tag(b,"published")[0]||tag(b,"updated")[0]||tag(b,"pubDate")[0]||tag(b,"dc:date")[0];const timestamp=published?Date.parse(published):NaN;if(title&&href&&Number.isFinite(timestamp)&&timestamp>=cutoff)out.push({title,summary,url:href,source:s.name,type:s.type,published_at:new Date(timestamp).toISOString()});}}catch(e){console.warn(`跳过 ${s.name}: ${e.message}`)}}return out}
async function issues(){if(!token)return[];const res=await fetch(`https://api.github.com/repos/${owner}/${repo}/issues?state=open&per_page=100`,{headers:{authorization:`Bearer ${token}`,accept:"application/vnd.github+json"}});if(!res.ok)throw new Error(`GitHub Issues: ${res.status}`);return(await res.json()).filter(x=>!x.pull_request&&x.title.startsWith("[投稿]")&&Date.parse(x.created_at)>=cutoff).map(x=>{const url=x.body?.match(/### 文章链接\s+([^\s]+)/)?.[1]||x.body?.match(/https?:\/\/[^\s]+/)?.[0]||"";const source=x.body?.match(/### 来源或公众号\s+([^\n]+)/)?.[1]?.trim()||"人工投递";const summary=x.body?.match(/### 为什么值得读\s+([\s\S]*?)(?:\n###|$)/)?.[1]?.trim()||"";return{title:x.title.replace(/^\[投稿\]\s*/,""),url,source,summary,type:"公众号",published_at:x.created_at,issue_number:x.number}}).filter(x=>x.url)}
async function githubRepos(){if(!token)return[];const since=new Date(cutoff).toISOString().slice(0,10);const queries=[`topic:artificial-intelligence created:>=${since}`,`topic:llm created:>=${since}`,`topic:ai-agents created:>=${since}`];const out=[];for(const q of queries){try{const res=await fetch(`https://api.github.com/search/repositories?q=${encodeURIComponent(q)}&sort=stars&order=desc&per_page=10`,{headers:{authorization:`Bearer ${token}`,accept:"application/vnd.github+json"}});if(!res.ok)throw new Error(String(res.status));for(const x of (await res.json()).items||[])out.push({title:`${x.full_name} · ${x.stargazers_count} stars`,summary:x.description||"",url:x.html_url,source:"GitHub 新项目",type:"开源",published_at:x.created_at,stars:x.stargazers_count});}catch(e){console.warn(`跳过 GitHub ${q}: ${e.message}`)}}return out}
const candidates=[...await feeds(),...await githubRepos(),...await issues()];const archive=JSON.parse(await fs.readFile("data/archive.json","utf8"));const seen=new Set(archive.map(x=>x.url));const fresh=candidates.filter((x,i,a)=>x.url&&!seen.has(x.url)&&a.findIndex(y=>y.url===x.url)===i);
console.log(`最近 7 天获取 ${candidates.length} 条，历史与链接去重后剩余 ${fresh.length} 条`);
if(!fresh.length)throw new Error("本周没有新的候选内容");
const schema={type:"object",additionalProperties:false,required:["issue","weekly_take","articles"],properties:{issue:{type:"string"},weekly_take:{type:"string"},articles:{type:"array",maxItems:10,items:{type:"object",additionalProperties:false,required:["type","source","title","summary","reader_gain","career_signal","startup_signal","action","read_time","url","score"],properties:{type:{type:"string"},source:{type:"string"},title:{type:"string"},summary:{type:"string"},reader_gain:{type:"string"},career_signal:{type:"string"},startup_signal:{type:"string"},action:{type:"string"},read_time:{type:"string"},url:{type:"string"},score:{type:"number"}}}}}};
const prompt=`你是“前沿周刊”的中文主编。它不是论文摘要站，而是一份帮助技术人判断就业方向、创业机会和产业变化的每周商业科技情报。

从候选中严格选择10篇（候选不足时可少于10篇），先按事件语义去重，同一事件优先官方或一手来源。选刊结构尽量满足：企业战略、产品发布与商业化2篇；行业变化、市场、融资或公司动态2篇；Agent、开发工具、开源项目与真实落地2篇；岗位、技能栈或工作方式变化1篇；可转化为创业切口的新需求或新场景1篇；论文最多2篇，且必须有强应用潜力，纯指标改进不选。

优先回答：谁正在付钱、用户行为哪里改变、什么能力开始稀缺、哪些旧流程可被重做、个人本周可以验证什么。降低宏大叙事、模型跑分、重复发布会新闻的权重。评分：决策价值25、信息增量20、产业影响20、可行动性15、可信度10、时效10。软文、标题党、无来源转载扣分。

标题有获得感但不可夸张；summary用2句话说明发生了什么、为什么现在重要；reader_gain总结认知收获；career_signal明确对求职、技能或岗位的启示，没有就写“暂无直接信号”；startup_signal明确客户、痛点或商业机会，没有就写“暂无直接信号”；action给出读者一周内可完成的具体动作。weekly_take写本周最重要的一条产业判断。候选：${JSON.stringify(fresh).slice(0,120000)}`;
const response=await fetch("https://api.deepseek.com/responses",{method:"POST",headers:{authorization:`Bearer ${apiKey}`,"content-type":"application/json"},body:JSON.stringify({model,input:prompt,max_output_tokens:12000,text:{format:{type:"json_schema",name:"weekly_digest",schema}}})});if(!response.ok)throw new Error(`DeepSeek: ${response.status} ${await response.text()}`);const raw=await response.json();const text=raw.output?.flatMap(x=>x.content||[]).find(x=>x.type==="output_text")?.text;if(!text)throw new Error("DeepSeek 未返回结构化结果");const digest=JSON.parse(text);await fs.writeFile("docs/data/latest.json",JSON.stringify(digest,null,2)+"\n");archive.push(...digest.articles.map(x=>({url:x.url,title:x.title,published_at:new Date().toISOString()})));await fs.writeFile("data/archive.json",JSON.stringify(archive.slice(-1000),null,2)+"\n");
