import fs from "node:fs/promises";

const owner=process.env.GITHUB_REPOSITORY?.split("/")[0]||"Ivy-forever18";
const repo=process.env.GITHUB_REPOSITORY?.split("/")[1]||"frontier-weekly";
const token=process.env.GITHUB_TOKEN;
const apiKey=process.env.DEEPSEEK_API_KEY;
const model=process.env.DEEPSEEK_MODEL||"deepseek-v4-flash";
if(!apiKey) throw new Error("请在 GitHub Actions Secrets 中配置 DEEPSEEK_API_KEY");

const strip=s=>String(s||"").replace(/<!\[CDATA\[|\]\]>/g,"").replace(/<[^>]+>/g," ").replace(/&amp;/g,"&").replace(/\s+/g," ").trim();
const tag=(xml,name)=>[...xml.matchAll(new RegExp(`<${name}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${name}>`,"gi"))].map(m=>strip(m[1]));
async function feeds(){const sources=JSON.parse(await fs.readFile("data/sources.json","utf8"));const out=[];for(const s of sources.filter(x=>x.enabled)){try{const xml=await fetch(s.url,{headers:{"user-agent":"frontier-weekly/1.0"}}).then(r=>{if(!r.ok)throw new Error(String(r.status));return r.text()});const blocks=[...xml.matchAll(/<(item|entry)(?:\s[^>]*)?>([\s\S]*?)<\/\1>/gi)].slice(0,30);for(const [, ,b] of blocks){const title=tag(b,"title")[0],summary=tag(b,"description")[0]||tag(b,"summary")[0]||"";const href=b.match(/<link[^>]+href=["']([^"']+)/i)?.[1]||tag(b,"link")[0];if(title&&href)out.push({title,summary,url:href,source:s.name,type:s.type});}}catch(e){console.warn(`跳过 ${s.name}: ${e.message}`)}}return out}
async function issues(){if(!token)return[];const res=await fetch(`https://api.github.com/repos/${owner}/${repo}/issues?state=open&per_page=100`,{headers:{authorization:`Bearer ${token}`,accept:"application/vnd.github+json"}});if(!res.ok)throw new Error(`GitHub Issues: ${res.status}`);return(await res.json()).filter(x=>!x.pull_request&&x.title.startsWith("[投稿]")).map(x=>{const url=x.body?.match(/### 文章链接\s+([^\s]+)/)?.[1]||x.body?.match(/https?:\/\/[^\s]+/)?.[0]||"";const source=x.body?.match(/### 来源或公众号\s+([^\n]+)/)?.[1]?.trim()||"人工投递";const summary=x.body?.match(/### 为什么值得读\s+([\s\S]*?)(?:\n###|$)/)?.[1]?.trim()||"";return{title:x.title.replace(/^\[投稿\]\s*/,""),url,source,summary,type:"公众号",issue_number:x.number}}).filter(x=>x.url)}
const candidates=[...await feeds(),...await issues()];const archive=JSON.parse(await fs.readFile("data/archive.json","utf8"));const seen=new Set(archive.map(x=>x.url));const fresh=candidates.filter((x,i,a)=>x.url&&!seen.has(x.url)&&a.findIndex(y=>y.url===x.url)===i);
if(!fresh.length)throw new Error("本周没有新的候选内容");
const schema={type:"object",additionalProperties:false,required:["issue","weekly_take","articles"],properties:{issue:{type:"string"},weekly_take:{type:"string"},articles:{type:"array",maxItems:10,items:{type:"object",additionalProperties:false,required:["type","source","title","summary","reader_gain","read_time","url","score"],properties:{type:{type:"string"},source:{type:"string"},title:{type:"string"},summary:{type:"string"},reader_gain:{type:"string"},read_time:{type:"string"},url:{type:"string"},score:{type:"number"}}}}}};
const prompt=`你是“前沿周刊”的中文主编。从候选中最多选择10篇真正值得读的AI、CS、Agent内容。先按主题/事件做语义去重，同一事件优先原始来源。评分：信息增量25、相关性20、实用价值20、可信度15、可读性10、时效10；软文、标题党、无来源转载扣分。标题要有获得感但不可夸张；summary说明发生什么和为什么重要；reader_gain用一句话说明读者具体得到什么。候选：${JSON.stringify(fresh).slice(0,120000)}`;
const response=await fetch("https://api.deepseek.com/responses",{method:"POST",headers:{authorization:`Bearer ${apiKey}`,"content-type":"application/json"},body:JSON.stringify({model,input:prompt,max_output_tokens:12000,text:{format:{type:"json_schema",name:"weekly_digest",schema}}})});if(!response.ok)throw new Error(`DeepSeek: ${response.status} ${await response.text()}`);const raw=await response.json();const text=raw.output?.flatMap(x=>x.content||[]).find(x=>x.type==="output_text")?.text;if(!text)throw new Error("DeepSeek 未返回结构化结果");const digest=JSON.parse(text);await fs.writeFile("docs/data/latest.json",JSON.stringify(digest,null,2)+"\n");archive.push(...digest.articles.map(x=>({url:x.url,title:x.title,published_at:new Date().toISOString()})));await fs.writeFile("data/archive.json",JSON.stringify(archive.slice(-1000),null,2)+"\n");
