import fs from "node:fs/promises";

const owner=process.env.GITHUB_REPOSITORY?.split("/")[0]||"Ivy-forever18";
const repo=process.env.GITHUB_REPOSITORY?.split("/")[1]||"frontier-weekly";
const token=process.env.GITHUB_TOKEN;
const apiKey=process.env.DEEPSEEK_API_KEY;
const model=process.env.DEEPSEEK_MODEL||"deepseek-v4-flash";
if(!apiKey) throw new Error("请在 GitHub Actions Secrets 中配置 DEEPSEEK_API_KEY");
const cutoff=Date.now()-7*24*60*60*1000;

const strip=s=>String(s||"").replace(/<!\[CDATA\[|\]\]>/g,"").replace(/<[^>]+>/g," ").replace(/&amp;/g,"&").replace(/\s+/g," ").trim();
const tag=(xml,name)=>[...xml.matchAll(new RegExp(`<${name}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${name}>`,"gi"))].map(m=>strip(m[1]));
async function feeds(){const sources=JSON.parse(await fs.readFile("data/sources.json","utf8"));const out=[];for(const s of sources.filter(x=>x.enabled)){try{const xml=await fetch(s.url,{headers:{"user-agent":"frontier-weekly/1.0"}}).then(r=>{if(!r.ok)throw new Error(String(r.status));return r.text()});const blocks=[...xml.matchAll(/<(item|entry)(?:\s[^>]*)?>([\s\S]*?)<\/\1>/gi)].slice(0,50);for(const [, ,b] of blocks){const title=tag(b,"title")[0],summary=tag(b,"description")[0]||tag(b,"summary")[0]||"";const href=b.match(/<link[^>]+href=["']([^"']+)/i)?.[1]||tag(b,"link")[0];const published=tag(b,"published")[0]||tag(b,"updated")[0]||tag(b,"pubDate")[0]||tag(b,"dc:date")[0];const timestamp=published?Date.parse(published):NaN;if(title&&href&&Number.isFinite(timestamp)&&timestamp>=cutoff)out.push({title,summary,url:href,source:s.name,company:s.company||s.name,type:s.type,published_at:new Date(timestamp).toISOString()});}}catch(e){console.warn(`跳过 ${s.name}: ${e.message}`)}}return out}
async function issues(){if(!token)return[];const res=await fetch(`https://api.github.com/repos/${owner}/${repo}/issues?state=open&per_page=100`,{headers:{authorization:`Bearer ${token}`,accept:"application/vnd.github+json"}});if(!res.ok)throw new Error(`GitHub Issues: ${res.status}`);return(await res.json()).filter(x=>!x.pull_request&&x.title.startsWith("[投稿]")&&Date.parse(x.created_at)>=cutoff).map(x=>{const url=x.body?.match(/### 文章链接\s+([^\s]+)/)?.[1]||x.body?.match(/https?:\/\/[^\s]+/)?.[0]||"";const source=x.body?.match(/### 来源或公众号\s+([^\n]+)/)?.[1]?.trim()||"人工投递";const summary=x.body?.match(/### 为什么值得读\s+([\s\S]*?)(?:\n###|$)/)?.[1]?.trim()||"";return{title:x.title.replace(/^\[投稿\]\s*/,""),url,source,company:source,summary,type:"公众号",published_at:x.created_at,issue_number:x.number}}).filter(x=>x.url)}
async function githubRepos(){if(!token)return[];const since=new Date(cutoff).toISOString().slice(0,10);const queries=[`topic:artificial-intelligence created:>=${since}`,`topic:llm created:>=${since}`,`topic:ai-agents created:>=${since}`];const out=[];for(const q of queries){try{const res=await fetch(`https://api.github.com/search/repositories?q=${encodeURIComponent(q)}&sort=stars&order=desc&per_page=10`,{headers:{authorization:`Bearer ${token}`,accept:"application/vnd.github+json"}});if(!res.ok)throw new Error(String(res.status));for(const x of (await res.json()).items||[])out.push({title:`${x.full_name} · ${x.stargazers_count} stars`,summary:x.description||"",url:x.html_url,source:"GitHub 新项目",company:"开源社区",type:"开源",published_at:x.created_at,stars:x.stargazers_count});}catch(e){console.warn(`跳过 GitHub ${q}: ${e.message}`)}}return out}
async function companyGithub(){if(!token)return[];const orgs=JSON.parse(await fs.readFile("data/github-orgs.json","utf8"));const out=[];for(const o of orgs.filter(x=>x.enabled)){try{const res=await fetch(`https://api.github.com/users/${o.org}/repos?sort=pushed&direction=desc&per_page=30`,{headers:{authorization:`Bearer ${token}`,accept:"application/vnd.github+json","user-agent":"frontier-weekly/1.0"}});if(!res.ok)throw new Error(String(res.status));for(const x of await res.json()){const recent=Date.parse(x.created_at)>=cutoff||Date.parse(x.pushed_at)>=cutoff;if(recent&&x.stargazers_count>=o.min_stars&&!x.archived&&!x.fork)out.push({title:`${o.company}开源 · ${x.name}`,summary:`${x.description||"本周有新代码更新"}（${x.stargazers_count} stars）`,url:x.html_url,source:`${o.company} GitHub`,company:o.company,type:"大厂开源",published_at:x.pushed_at,stars:x.stargazers_count});}}catch(e){console.warn(`跳过 ${o.company} GitHub: ${e.message}`)}}return out}
async function companyWeb(){const sources=JSON.parse(await fs.readFile("data/web-sources.json","utf8"));const out=[];const aiWords=/AI|人工智能|大模型|模型|Agent|智能体|开源|工程|云原生|数据库|推荐|搜索|研发|开发|架构/i;for(const s of sources.filter(x=>x.enabled)){try{const html=await fetch(s.url,{headers:{"user-agent":"Mozilla/5.0 frontier-weekly/1.0"}}).then(r=>{if(!r.ok)throw new Error(String(r.status));return r.text()});for(const m of html.matchAll(/<a\b[^>]*href=["']([^"'#]+)["'][^>]*>([\s\S]*?)<\/a>/gi)){const title=strip(m[2]);if(title.length<8||title.length>100||!aiWords.test(title))continue;const nearby=html.slice(Math.max(0,m.index-300),m.index+m[0].length+500);const date=nearby.match(/(20\d{2})[年\-\/.](\d{1,2})[月\-\/.](\d{1,2})日?/);if(!date)continue;const timestamp=Date.parse(`${date[1]}-${date[2].padStart(2,"0")}-${date[3].padStart(2,"0")}T00:00:00+08:00`);if(timestamp<cutoff)continue;const url=new URL(m[1],s.url).href;out.push({title,summary:`来自${s.name}的最新官方内容`,url,source:s.name,company:s.company,type:s.type,published_at:new Date(timestamp).toISOString()});}}catch(e){console.warn(`跳过 ${s.name}: ${e.message}`)}}return out}
const candidates=[...await feeds(),...await companyWeb(),...await companyGithub(),...await githubRepos(),...await issues()];const archive=JSON.parse(await fs.readFile("data/archive.json","utf8"));const seen=new Set(archive.map(x=>x.url));const fresh=candidates.filter((x,i,a)=>x.url&&!seen.has(x.url)&&a.findIndex(y=>y.url===x.url)===i);
console.log(`最近 7 天获取 ${candidates.length} 条，历史与链接去重后剩余 ${fresh.length} 条`);
if(!fresh.length)throw new Error("本周没有新的候选内容");
const policyWords=/\b(policy|regulation|regulatory|government|congress|senate|lawmakers|legislation|executive order|white house|election)\b|政策|监管|法规|立法|国会|政府|选举|行政令/i;
const editorial=fresh.filter(x=>!policyWords.test(`${x.title} ${x.summary}`));
const bySource=new Map();
for(const x of editorial){const items=bySource.get(x.source)||[];if(items.length<12){items.push({...x,summary:x.summary.slice(0,450)});bySource.set(x.source,items)}}
const balanced=[];for(let i=0;i<12;i++)for(const items of bySource.values())if(items[i])balanced.push(items[i]);
console.log(`排除政策类后 ${editorial.length} 条；按来源均衡后 ${balanced.length} 条，覆盖 ${bySource.size} 个来源`);
if(!balanced.length)throw new Error("本周没有符合编辑方向的候选内容");
const schema={type:"object",additionalProperties:false,required:["issue","weekly_take","articles"],properties:{issue:{type:"string"},weekly_take:{type:"string"},articles:{type:"array",maxItems:10,items:{type:"object",additionalProperties:false,required:["type","source","title","summary","reader_gain","career_signal","startup_signal","action","read_time","url","score"],properties:{type:{type:"string"},source:{type:"string"},title:{type:"string"},summary:{type:"string"},reader_gain:{type:"string"},career_signal:{type:"string"},startup_signal:{type:"string"},action:{type:"string"},read_time:{type:"string"},url:{type:"string"},score:{type:"number"}}}}}};
const prompt=`你是“前沿周刊”的中文主编。它不是论文摘要站，而是一份帮助技术人判断就业方向、创业机会和产业变化的每周商业科技情报。

从候选中最多选择10篇（可少于10篇），先按事件语义去重。每个来源最多2篇，同一家企业相关的文章最多2篇；优先让至少5家不同的企业、媒体或开源社区进入一期，不要被OpenAI或任何单一公司主导。同一事件优先官方或一手来源。选刊结构尽量满足：企业战略、产品发布与商业化2篇；行业变化、市场、融资或公司动态2篇；Agent、开发工具、开源项目与真实落地2篇；岗位、技能栈或工作方式变化1篇；可转化为创业切口的新需求或新场景1篇；论文最多2篇，且必须有强应用潜力，纯指标改进不选。完全不要政策、监管、法律、政府倡议、地缘政治、宏观立场类文章。若候选不足，宁可少于10篇，也不要凑数。

优先回答：谁正在付钱、用户行为哪里改变、什么能力开始稀缺、哪些旧流程可被重做、个人本周可以验证什么。降低宏大叙事、模型跑分、重复发布会新闻的权重。评分：决策价值25、信息增量20、产业影响20、可行动性15、可信度10、时效10。软文、标题党、无来源转载扣分。

为避免输出被截断，必须简洁：summary最多90个汉字，其余说明字段各最多55个汉字，weekly_take最多180个汉字。标题有获得感但不可夸张；reader_gain总结认知收获；career_signal明确就业启示；startup_signal明确客户、痛点或商业机会；action给出一周内可完成的动作。没有直接信号就写“暂无直接信号”。url和source必须逐字复制候选里的纯文本值，url严禁写成Markdown链接，不能编造。候选：${JSON.stringify(balanced).slice(0,120000)}`;
async function curate(){let lastError;for(let attempt=1;attempt<=2;attempt++){const retry=attempt===1?"":"\n上一次输出不是完整JSON。请重新生成更短的完整JSON，绝对不要在字段限制之外扩写。";const response=await fetch("https://api.deepseek.com/responses",{method:"POST",headers:{authorization:`Bearer ${apiKey}`,"content-type":"application/json"},body:JSON.stringify({model,input:prompt+retry,max_output_tokens:16000,text:{format:{type:"json_schema",name:"weekly_digest",schema}}})});if(!response.ok)throw new Error(`DeepSeek: ${response.status} ${await response.text()}`);const raw=await response.json();const text=raw.output?.flatMap(x=>x.content||[]).find(x=>x.type==="output_text")?.text;if(!text){lastError=new Error("DeepSeek 未返回结构化结果");continue}try{return JSON.parse(text)}catch(e){lastError=e;console.warn(`DeepSeek 第 ${attempt} 次返回的 JSON 不完整，准备重试`)}}throw new Error(`DeepSeek 连续两次未返回完整 JSON: ${lastError?.message}`)}
const digest=await curate();
const lookup=new Map(balanced.map(x=>[x.url,x]));const perSource=new Map(),perCompany=new Map();let papers=0;const articles=[];
for(const a of digest.articles){const url=String(a.url).match(/\((https?:\/\/[^)]+)\)\s*$/)?.[1]||String(a.url).replace(/^<|>$/g,"");const original=lookup.get(url);if(!original||policyWords.test(`${original.title} ${a.title} ${a.summary}`))continue;const sourceCount=perSource.get(original.source)||0,companyCount=perCompany.get(original.company)||0;if(sourceCount>=2||companyCount>=2||original.type==="论文"&&papers>=2)continue;perSource.set(original.source,sourceCount+1);perCompany.set(original.company,companyCount+1);if(original.type==="论文")papers++;articles.push({...a,source:original.source,url:original.url});if(articles.length===10)break}
if(!articles.length)throw new Error("AI 返回内容未通过来源与政策校验，本期不发布");
digest.articles=articles;console.log(`最终入选 ${articles.length} 篇，来源：${[...perSource].map(([s,n])=>`${s} ${n}`).join("、")}`);
await fs.writeFile("docs/data/latest.json",JSON.stringify(digest,null,2)+"\n");archive.push(...articles.map(x=>({url:x.url,title:x.title,published_at:new Date().toISOString()})));await fs.writeFile("data/archive.json",JSON.stringify(archive.slice(-1000),null,2)+"\n");
